from pathlib import Path

from invoke import task

from . import ui, util

_IDENTITY_PATH = Path.home() / ".config" / "pulse" / "identity.toml"
_EXAMPLE_PATH = Path(__file__).parent.parent / "config" / "identity.toml.example"

# label -> real hostname; simple mode uses the hostname itself as the ssh_hosts alias since
# there's only ever one account per host in this mode (no need to disambiguate with a custom
# alias the way the multi-account advanced setup does).
_HOSTS = {
    "GitHub": "github.com",
    "GitLab": "gitlab.com",
}


def _toml_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _render(name: str, email: str, directory: str, hosts: list[str]) -> str:
    lines = [
        "# Personal identity data — DO NOT commit this file.",
        "# Generated by `inv identity.init` (simple single-identity setup).",
        "#",
        "# This is the same schema config/identity.toml.example uses — add more",
        "# [[git_profiles]] / [[ssh_hosts]] entries by hand later if you outgrow a single",
        "# identity (e.g. a separate work account); see that file and docs/git.md / docs/ssh.md.",
        "",
        "[[git_profiles]]",
        f"directory = {_toml_string(directory)}",
        f"name      = {_toml_string(name)}",
        f"email     = {_toml_string(email)}",
    ]
    for label in hosts:
        hostname = _HOSTS[label]
        lines += [
            "",
            "[[ssh_hosts]]",
            'user     = "git"',
            f"alias    = {_toml_string(hostname)}",
            f"hostname = {_toml_string(hostname)}",
            f"email    = {_toml_string(email)}",
        ]
    return "\n".join(lines) + "\n"


@task
def init(c):
    """Interactive wizard for ~/.config/pulse/identity.toml: pick simple (one name/email, one
    ~/projects/<dir>/) or advanced (hand-edit the full multi-directory/multi-host example).

    Writes the same identity.toml schema either way — git.py/ssh.py don't know or care which
    path produced the file, and a simple-mode file is trivially expandable later by hand.
    """
    if not util.interactive():
        print("[identity] not an interactive terminal — nothing to do.")
        print(f"[identity] copy {_EXAMPLE_PATH} to {_IDENTITY_PATH} and edit it by hand instead.")
        return

    ui.block(
        "Simple: one name/email, one ~/projects/<dir>/ directory. Quick, and easy to expand "
        "into more directories/hosts later by hand.",
        "Advanced: hand-edit identity.toml yourself for multiple directories, accounts, or server hosts right away.",
        label="identity setup",
    )
    if not ui.ask("Use the simple single-identity setup?", default=True):
        print(f"[identity] cp {_EXAMPLE_PATH} {_IDENTITY_PATH}")
        print("[identity] then edit it by hand — see docs/git.md and docs/ssh.md.")
        return

    if _IDENTITY_PATH.exists() and not ui.ask(f"{_IDENTITY_PATH} already exists — overwrite it?", default=False):
        print("[identity] left existing file untouched.")
        return

    name = util.prompt_text("Full name (for git commits)")
    email = util.prompt_text("Email address")
    directory = util.prompt_text("Projects subdirectory name (~/projects/<this>/)", default="default")

    hosts = [label for label in _HOSTS if ui.ask(f"Set up SSH/git for {label}?", default=label == "GitHub")]
    if not hosts:
        print("[identity] no hosts selected — add [[ssh_hosts]] entries by hand later if you need one.")

    _IDENTITY_PATH.parent.mkdir(mode=0o700, parents=True, exist_ok=True)
    _IDENTITY_PATH.write_text(_render(name, email, directory, hosts))
    _IDENTITY_PATH.chmod(0o600)
    print(f"[identity] wrote {_IDENTITY_PATH}")
    print("[identity] next: inv git.configure git.settings ssh.keys ssh.configure ssh.add")
