from pathlib import Path

from invoke import Context, task

from . import ui, util

_EXAMPLE_PATH = Path(__file__).parent.parent / "config" / "identity.toml.example"

# label -> real hostname; simple mode uses the hostname itself as the ssh_hosts alias since
# there's only ever one account per host in this mode (no need to disambiguate with a custom
# alias the way the multi-account advanced setup does).
_HOST_LABELS = {
    "GitHub": "github.com",
    "GitLab": "gitlab.com",
}


def _toml_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _render(name: str, email: str, directory: str, hosts: list[str]) -> str:
    lines = [
        "# Personal identity data — DO NOT commit this file.",
        "# Generated by `inv identity.init` (simple single-identity setup).",
        "#",
        "# This is the same schema config/identity.toml.example uses — add more",
        "# [[git_profiles]] / [[ssh_hosts]] entries by hand later if you outgrow a single",
        "# identity (e.g. a separate work account); see that file and docs/git.md / docs/ssh.md.",
        "",
        "[[git_profiles]]",
        f"directory = {_toml_string(directory)}",
        f"name      = {_toml_string(name)}",
        f"email     = {_toml_string(email)}",
    ]
    for label in hosts:
        hostname = _HOST_LABELS[label]
        lines += [
            "",
            "[[ssh_hosts]]",
            'user     = "git"',
            f"alias    = {_toml_string(hostname)}",
            f"hostname = {_toml_string(hostname)}",
            f"email    = {_toml_string(email)}",
        ]
    return "\n".join(lines) + "\n"


@task
def init(c: Context):
    """Interactive wizard for ~/.config/power-user-linux-setup/identity.toml: pick simple (one
    name/email, one projects directory — ~/projects/ by default) or advanced (hand-edit the full
    multi-directory/multi-host example).

    Writes the same identity.toml schema either way — git.py/ssh.py don't know or care which
    path produced the file, and a simple-mode file is trivially expandable later by hand.
    """
    if not util.interactive():
        print("[identity] not an interactive terminal — nothing to do.")
        print(f"[identity] copy {_EXAMPLE_PATH} to {util.IDENTITY_PATH} and edit it by hand instead.")
        return

    ui.block(
        "Simple: one name/email, one projects directory (defaults to ~/projects/ itself — enter "
        "an absolute path, ~ allowed, to use somewhere else instead). Quick, and easy to expand "
        "into more directories/hosts later by hand.",
        "Advanced: hand-edit identity.toml yourself for multiple directories, accounts, or server hosts right away.",
        label="identity setup",
    )
    if not ui.ask("Use the simple single-identity setup?", default=True):
        print(f"[identity] cp {_EXAMPLE_PATH} {util.IDENTITY_PATH}")
        print("[identity] then edit it by hand — see docs/git.md and docs/ssh.md.")
        return

    overwrite_prompt = f"{util.IDENTITY_PATH} already exists — overwrite it?"
    if util.IDENTITY_PATH.exists() and not ui.ask(overwrite_prompt, default=False):
        print("[identity] left existing file untouched.")
        return

    # None-return in prompt_text() is only reachable via its own non-interactive branch — this
    # function already returned above when util.interactive() is False, so stdin is guaranteed a
    # real tty here and these three prompts always give a real answer, not None.
    name = util.prompt_text("Full name (for git commits)")
    assert name is not None
    email = util.prompt_text("Email address")
    assert email is not None
    directory = util.prompt_text(
        "Projects directory (absolute path, ~ allowed, as many nested dirs as you like)",
        default="~/projects/",
    )
    assert directory is not None

    hosts = [label for label in _HOST_LABELS if ui.ask(f"Set up SSH/git for {label}?", default=label == "GitHub")]
    if not hosts:
        print("[identity] no hosts selected — add [[ssh_hosts]] entries by hand later if you need one.")

    util.IDENTITY_PATH.parent.mkdir(mode=0o700, parents=True, exist_ok=True)
    util.IDENTITY_PATH.write_text(_render(name, email, directory, hosts))
    util.IDENTITY_PATH.chmod(0o600)
    print(f"[identity] wrote {util.IDENTITY_PATH}")
    print("[identity] next: inv git.configure git.apply-settings ssh.create-keys ssh.configure ssh.add")
