import os
import tempfile
from pathlib import Path

from invoke import task

from . import apt, node, python, system, tools, util, zsh

_WSL_CONF   = Path("/etc/wsl.conf")
_RESOLV_CONF = Path("/etc/resolv.conf")
_STUB_RESOLV_CONF = Path("/run/systemd/resolve/stub-resolv.conf")
_PROC_VERSION  = Path("/proc/version")
_OSRELEASE     = Path("/proc/sys/kernel/osrelease")


def _is_wsl() -> bool:
    if os.environ.get("WSL_DISTRO_NAME") or os.environ.get("WSL_INTEROP"):
        return True
    try:
        return "microsoft" in _PROC_VERSION.read_text().lower()
    except FileNotFoundError:
        return False


def _is_wsl2() -> bool:
    try:
        release = _OSRELEASE.read_text().lower()
    except FileNotFoundError:
        return False
    return "wsl2" in release or "microsoft-standard" in release


def _systemd_running() -> bool:
    return Path("/run/systemd/system").is_dir()


def _wsl_conf_value(section: str, key: str) -> str | None:
    """Read a single key out of /etc/wsl.conf's INI format. Returns None if unset."""
    if not _WSL_CONF.exists():
        return None
    current = None
    for line in _WSL_CONF.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or line.startswith(";"):
            continue
        if line.startswith("[") and line.endswith("]"):
            current = line[1:-1].strip().lower()
            continue
        if current == section and "=" in line:
            k, _, v = line.partition("=")
            if k.strip().lower() == key.lower():
                return v.strip()
    return None


def _ensure_wsl_conf_kv(text: str, section: str, key: str, value: str) -> tuple[str, bool]:
    """Idempotently set `key = value` under [section] in wsl.conf-style INI text.

    Preserves everything else in the file (other sections/keys/comments) — this is user-owned
    config, not a PULSE-managed block, so it can't just be overwritten wholesale like
    util.ensure_block does elsewhere. Returns (new_text, changed).
    """
    lines = text.splitlines()
    header = f"[{section}]"
    sec_start = None
    sec_end = len(lines)
    for i, line in enumerate(lines):
        if line.strip().lower() == header.lower():
            sec_start = i
            sec_end = len(lines)
            for j in range(i + 1, len(lines)):
                stripped = lines[j].strip()
                if stripped.startswith("[") and stripped.endswith("]"):
                    sec_end = j
                    break
            break

    if sec_start is None:
        if lines and lines[-1].strip() != "":
            lines.append("")
        lines += [header, f"{key} = {value}"]
        return "\n".join(lines) + "\n", True

    for i in range(sec_start + 1, sec_end):
        stripped = lines[i].strip()
        if not stripped or stripped.startswith("#") or stripped.startswith(";") or "=" not in stripped:
            continue
        k, _, v = stripped.partition("=")
        if k.strip().lower() == key.lower():
            if v.strip() == value:
                return text, False
            lines[i] = f"{key} = {value}"
            return "\n".join(lines) + "\n", True

    lines.insert(sec_end, f"{key} = {value}")
    return "\n".join(lines) + "\n", True


def _resolv_conf_wsl_active() -> bool:
    """True if WSL is still (or will still, pending restart) overwrite /etc/resolv.conf itself —
    i.e. generateResolvConf hasn't been set to false in /etc/wsl.conf yet. False once it has, even
    if the file's *content* still shows the old "automatically generated by WSL" comment: WSL
    stops touching the file once that setting takes effect, it doesn't revert what's already
    there, so content alone isn't a reliable signal of what WSL will do next.
    """
    gen = _wsl_conf_value("network", "generateResolvConf")
    return not (gen is not None and gen.lower() == "false")


def _resolv_conf_symlinked_to_stub() -> bool:
    """Stock Ubuntu ships /etc/resolv.conf as a symlink to systemd-resolved's stub resolver.

    WSL's generateResolvConf overwrites that symlink with a plain file on every boot. Setting
    generateResolvConf=false only stops WSL from touching the file going forward — it does not
    restore the symlink, so the stale plain file (still containing the "automatically generated
    by WSL" comment, since nothing has rewritten it) is left in place. `inv system.dns` only
    edits systemd-resolved's own drop-in config, same as on bare metal, so with the symlink
    missing it has nothing to point at and DNS keeps failing (curl error 6) until the symlink is
    restored.
    """
    return _RESOLV_CONF.is_symlink() and os.path.realpath(_RESOLV_CONF) == os.path.realpath(_STUB_RESOLV_CONF)


def _wslg_available() -> bool:
    return Path("/mnt/wslg").exists() or bool(os.environ.get("WAYLAND_DISPLAY"))


def _os_release_id() -> str:
    try:
        text = Path("/etc/os-release").read_text()
    except FileNotFoundError:
        return ""
    for line in text.splitlines():
        if line.startswith("ID="):
            return line.partition("=")[2].strip().strip('"')
    return ""


@task
def check(c):
    """Diagnose WSL-specific risks before running PULSE tasks: systemd, DNS, Docker, WSLg.

    Read-only — reports findings and remediation, changes nothing. See docs/wsl.md.
    """
    if not _is_wsl():
        print("[wsl] not running under WSL — nothing to check")
        return

    if _is_wsl2():
        print("[wsl] WSL2 detected")
    else:
        print(
            "[wsl] WSL1 detected  ← WARNING: WSL1 has no real Linux kernel (syscall translation "
            "layer only). systemd does not run under WSL1 at all, so every check below will fail "
            "and most of PULSE's system.* and docker.* tasks are not usable. Upgrade to WSL2:\n"
            "       wsl.exe --set-version <distro> 2   (run from Windows)"
        )

    # Distro — WSL isn't Ubuntu-only (Debian, Kali, Alpine, Fedora Remix, openSUSE, Arch are all
    # available from the Microsoft Store); PULSE assumes apt/dpkg everywhere (apt, apt-repo,
    # deb-github, deb-url methods) and Ubuntu specifically for apt.repos (uses `lsb_release -cs` as
    # the codename in repo source lines) and apt.base's package set.
    os_id = _os_release_id()
    if os_id == "ubuntu":
        print("[wsl] distro: Ubuntu ✓")
    elif util.command_exists("apt"):
        print(
            f"[wsl] distro: {os_id or 'unknown'} — has apt, but PULSE is only tested against "
            "Ubuntu 24.04.  ← apt/apt-repo/deb-github/deb-url methods should work; anything "
            "assuming Ubuntu specifically (apt.repos' `lsb_release -cs` codename in repo source "
            "lines, apt.base's exact package names) may not resolve or may pull the wrong repo."
        )
    else:
        print(
            f"[wsl] distro: {os_id or 'unknown'} — no `apt` found.  ← PULSE assumes apt/dpkg "
            "throughout (apt, apt-repo, deb-github, deb-url methods); almost none of this repo "
            "will work here as-is. Install Ubuntu-24.04 from the Microsoft Store instead:\n"
            "       wsl.exe --install Ubuntu-24.04   (run from Windows)"
        )

    # systemd — gates system.locale, system.dns, system.journal_size, docker.configure
    if _systemd_running():
        print("[wsl] systemd: running ✓")
    else:
        print(
            "[wsl] systemd: NOT running  ← system.locale, system.dns, system.journal-size, and "
            "docker.configure now abort immediately instead of failing partway (util.require_systemd).\n"
            "       Fix: `inv wsl.fix` sets systemd=true in /etc/wsl.conf, then `wsl.exe --shutdown` "
            "from Windows and reopen the terminal."
        )

    # DNS — WSL regenerates /etc/resolv.conf from the Windows host on every restart by default
    _RELINK_CMD = f"sudo ln -sf {_STUB_RESOLV_CONF} /etc/resolv.conf"
    if _resolv_conf_wsl_active():
        print(
            "[wsl] resolv.conf: auto-generated by WSL  ← inv system.dns writes a systemd-resolved "
            "drop-in that will be silently overwritten on every WSL restart.\n"
            "       Fix: `inv wsl.fix` sets generateResolvConf=false in /etc/wsl.conf, then "
            f"`wsl.exe --shutdown`, reopen, `{_RELINK_CMD}`, and re-run `inv system.dns`."
        )
    elif _resolv_conf_symlinked_to_stub():
        print("[wsl] resolv.conf: not WSL-managed ✓ (inv system.dns is safe to use)")
    else:
        print(
            "[wsl] resolv.conf: generateResolvConf=false is set, but /etc/resolv.conf isn't a "
            "symlink to systemd-resolved's stub yet  ← inv system.dns edits systemd-resolved's own "
            "config and won't have any effect until this is fixed. If you just restarted, this is "
            "the stale file WSL left behind — WSL doesn't restore the symlink on its own.\n"
            f"       Fix: `{_RELINK_CMD}` then `inv system.dns`."
        )

    # Docker — native dockerd (systemctl-manageable) vs Docker Desktop's WSL integration (CLI only)
    if util.command_exists("docker"):
        if util.command_exists("dockerd"):
            print("[wsl] docker: native dockerd found ✓ (docker.configure's systemctl calls apply normally)")
        else:
            print(
                "[wsl] docker: `docker` CLI found but no local dockerd — this looks like Docker "
                "Desktop's WSL integration.  ← docker.configure's `systemctl restart docker` will fail: "
                "there is no local docker.service to manage.\n"
                "       Either leave [packages.docker] excluded (workstation tag) and manage Docker "
                "Desktop settings from Windows, or install docker-ce natively in this distro "
                "(don't exclude the workstation tag) to use docker.configure as-is."
            )
    else:
        print("[wsl] docker: not installed — nothing to check")

    # WSLg — gates GUI apps and Wayland clipboard
    if _wslg_available():
        print(
            "[wsl] WSLg: available ✓ — gui/desktop packages work, but install as little as "
            "possible: PULSE_EXCLUDE_TAGS=gnome,ide,windows-native,workstation,corporate\n"
            "       See docs/wsl.md, \"GUI, WSLg, and clipboard\" for why."
        )
    else:
        print(
            "[wsl] WSLg: not detected — [packages.clipboard] (wl-clipboard) and any gui/desktop/gnome-"
            "tagged package will not work. Use PULSE_EXCLUDE_TAGS=gui,desktop,gnome,workstation,corporate."
        )

    # Fonts — cannot be checked or fixed from inside WSL; always worth the reminder
    print(
        "[wsl] fonts: inv fonts.install only installs into ~/.local/share/fonts inside this distro — "
        "invisible to Windows Terminal or any other Windows-side app. Install the Nerd Font on the "
        "Windows side manually for terminal glyphs to render correctly."
    )


@task
def fix(c):
    """Fix common /etc/wsl.conf misconfigurations: systemd=true, generateResolvConf=false.

    Only touches settings that are actually fixable from inside the distro — distro choice, WSL1
    vs WSL2, and WSLg availability all require action on the Windows side (see `inv wsl.check`
    for those). Requires a full WSL restart (`wsl.exe --shutdown` from Windows) to take effect.
    """
    if not _is_wsl():
        print("[wsl] not running under WSL — nothing to fix")
        return

    text = _WSL_CONF.read_text() if _WSL_CONF.exists() else ""
    new_text, systemd_changed = _ensure_wsl_conf_kv(text, "boot", "systemd", "true")
    new_text, dns_changed = _ensure_wsl_conf_kv(new_text, "network", "generateResolvConf", "false")

    if util.DRY_RUN:
        print(f"[wsl.fix] systemd=true: {'MISSING' if systemd_changed else 'ok'}")
        print(f"[wsl.fix] generateResolvConf=false: {'MISSING' if dns_changed else 'ok'}")
        return

    if not (systemd_changed or dns_changed):
        print("[wsl.fix] /etc/wsl.conf already has systemd=true and generateResolvConf=false — nothing to do")
        return

    with tempfile.NamedTemporaryFile("w", suffix=".conf", delete=False) as f:
        f.write(new_text)
        tmp = f.name
    c.run(f"{util.SUDO} mkdir -p {_WSL_CONF.parent} && {util.SUDO} cp {tmp} {_WSL_CONF} && rm {tmp}")

    fixed = ", ".join(
        name for name, changed in (("systemd", systemd_changed), ("generateResolvConf", dns_changed)) if changed
    )
    print(f"[wsl.fix] /etc/wsl.conf updated ({fixed})")
    print(
        "[wsl.fix] Takes effect only after a full WSL restart — from Windows (PowerShell/cmd, not "
        "from inside this distro): `wsl.exe --shutdown`, then reopen your terminal."
    )
    if dns_changed:
        print(
            "[wsl.fix] After restarting: /etc/resolv.conf will still be the stale WSL-written file "
            "— WSL doesn't restore the systemd-resolved symlink on its own. Run "
            f"`sudo ln -sf {_STUB_RESOLV_CONF} /etc/resolv.conf` then `inv system.dns` "
            "(or just `inv wsl.install`, which does this for you) — see docs/wsl.md."
        )


@task
def install(c, wslg="auto", docker=False):
    """Run the docs/wsl.md recommended install sequence in one shot: check, fix, system.locale/
    system.dns (only if systemd/DNS are actually live yet), then apt/tools/language/zsh setup
    with WSL-appropriate tags excluded.

    This exists instead of pasting the multi-line sequence from docs/wsl.md into a terminal:
    that sequence is a series of separate `inv` invocations, so if one of them hangs (e.g. a
    network problem mid-apt) and you Ctrl-C it, the shell just moves on to the next already-
    pasted line rather than stopping — it looks like Ctrl-C "did nothing". Running everything
    as task calls inside one invoke process means Ctrl-C here aborts the whole thing.

    wslg: "auto" (default, detected the same way `inv wsl.check` does), "yes", or "no" — controls
      which tag set is excluded (see docs/wsl.md, "Tags to exclude").
    docker: pass --docker to also install Docker natively (drops the `workstation` tag exclusion)
      instead of leaving Docker to Docker Desktop's WSL integration.
    """
    if not _is_wsl():
        print("[wsl.install] not running under WSL — nothing to do")
        return

    check(c)

    pre = (_wsl_conf_value("boot", "systemd"), _wsl_conf_value("network", "generateResolvConf"))
    fix(c)
    post = (_wsl_conf_value("boot", "systemd"), _wsl_conf_value("network", "generateResolvConf"))
    if pre != post:
        print(
            "[wsl.install] /etc/wsl.conf just changed — system.locale/system.dns below will be "
            "skipped until you `wsl.exe --shutdown` (from Windows) and reopen, then re-run "
            "`inv wsl.install`. Continuing with the rest of the install now."
        )

    # Fix locale/DNS *before* anything network-dependent below (apt, tools.install, node, zsh's
    # oh-my-zsh clone, ...): if this is a re-run after a restart and generateResolvConf=false is
    # already live, DNS is broken (stale resolv.conf, see _resolv_conf_symlinked_to_stub) until
    # this runs — doing it last meant every one of those steps hit the same DNS failure first.
    if _systemd_running():
        system.locale(c)
    else:
        print("[wsl.install] systemd not live yet — skipping system.locale (restart WSL and re-run)")

    if _systemd_running() and not _resolv_conf_wsl_active():
        if not _resolv_conf_symlinked_to_stub():
            if util.DRY_RUN:
                print("[wsl.install] /etc/resolv.conf: MISSING symlink to stub-resolv.conf")
            else:
                c.run(f"{util.SUDO} ln -sf {_STUB_RESOLV_CONF} {_RESOLV_CONF}")
                print(f"[wsl.install] relinked /etc/resolv.conf -> {_STUB_RESOLV_CONF}")
        system.dns(c)
    else:
        print("[wsl.install] systemd/DNS not both live yet — skipping system.dns (restart WSL and re-run)")

    if wslg == "auto":
        use_wslg = _wslg_available()
    elif wslg in ("yes", "true", "1"):
        use_wslg = True
    elif wslg in ("no", "false", "0"):
        use_wslg = False
    else:
        raise RuntimeError(f"--wslg must be auto, yes, or no (got {wslg!r})")

    if use_wslg:
        excluded = {"gnome", "ide", "windows-native", "workstation", "corporate"}
    else:
        excluded = {"gui", "desktop", "gnome", "workstation", "corporate"}
    if docker:
        excluded.discard("workstation")

    if "PULSE_EXCLUDE_TAGS" in os.environ:
        print(
            f"[wsl.install] PULSE_EXCLUDE_TAGS already set in the environment "
            f"({os.environ['PULSE_EXCLUDE_TAGS']!r}) — using it as-is instead of the WSL default"
        )
    else:
        os.environ["PULSE_EXCLUDE_TAGS"] = ",".join(sorted(excluded))
        print(f"[wsl.install] PULSE_EXCLUDE_TAGS={os.environ['PULSE_EXCLUDE_TAGS']}")

    apt.repos(c)
    apt.base(c)
    apt.deb(c)
    tools.install(c)
    python.tools(c)
    node.install(c)
    zsh.omz_configure(c)
    zsh.configure(c)
    zsh.p10k_configure(c)

    if docker:
        print("[wsl.install] --docker: run `inv docker.configure` once systemd is confirmed live (`inv wsl.check`).")
