import os
import socket
import struct
import tempfile
from pathlib import Path

from invoke import task

from . import ai, apt, next_steps, node, phases, python, system, tools, ui, util, verify, zsh

_WSL_CONF = Path("/etc/wsl.conf")
_RESOLV_CONF = Path("/etc/resolv.conf")
_STUB_RESOLV_CONF = Path("/run/systemd/resolve/stub-resolv.conf")
_OSRELEASE = Path("/proc/sys/kernel/osrelease")


def _is_wsl2() -> bool:
    try:
        release = _OSRELEASE.read_text().lower()
    except FileNotFoundError:
        return False
    return "wsl2" in release or "microsoft-standard" in release


def _systemd_running() -> bool:
    return Path("/run/systemd/system").is_dir()


def _wsl_conf_value(section: str, key: str) -> str | None:
    """Read a single key out of /etc/wsl.conf's INI format. Returns None if unset."""
    if not _WSL_CONF.exists():
        return None
    current = None
    for line in _WSL_CONF.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or line.startswith(";"):
            continue
        if line.startswith("[") and line.endswith("]"):
            current = line[1:-1].strip().lower()
            continue
        if current == section and "=" in line:
            k, _, v = line.partition("=")
            if k.strip().lower() == key.lower():
                return v.strip()
    return None


def _ensure_wsl_conf_kv(text: str, section: str, key: str, value: str) -> tuple[str, bool]:
    """Idempotently set `key = value` under [section] in wsl.conf-style INI text.

    Preserves everything else in the file (other sections/keys/comments) — this is user-owned
    config, not a PULSE-managed block, so it can't just be overwritten wholesale like
    util.ensure_block does elsewhere. Returns (new_text, changed).
    """
    lines = text.splitlines()
    header = f"[{section}]"
    sec_start = None
    sec_end = len(lines)
    for i, line in enumerate(lines):
        if line.strip().lower() == header.lower():
            sec_start = i
            sec_end = len(lines)
            for j in range(i + 1, len(lines)):
                stripped = lines[j].strip()
                if stripped.startswith("[") and stripped.endswith("]"):
                    sec_end = j
                    break
            break

    if sec_start is None:
        if lines and lines[-1].strip() != "":
            lines.append("")
        lines += [header, f"{key} = {value}"]
        return "\n".join(lines) + "\n", True

    for i in range(sec_start + 1, sec_end):
        stripped = lines[i].strip()
        if not stripped or stripped.startswith("#") or stripped.startswith(";") or "=" not in stripped:
            continue
        k, _, v = stripped.partition("=")
        if k.strip().lower() == key.lower():
            if v.strip() == value:
                return text, False
            lines[i] = f"{key} = {value}"
            return "\n".join(lines) + "\n", True

    lines.insert(sec_end, f"{key} = {value}")
    return "\n".join(lines) + "\n", True


def _parse_tristate(value: str, flag_name: str) -> bool:
    """Parse a --dns/--wslg-style explicit yes/no override — "auto" is handled separately by
    each caller, since what "auto" means differs per flag."""
    if value in ("yes", "true", "1"):
        return True
    if value in ("no", "false", "0"):
        return False
    raise RuntimeError(f"--{flag_name} must be auto, yes, or no (got {value!r})")


def _resolv_conf_wsl_active() -> bool:
    """True if WSL is still (or will still, pending restart) overwrite /etc/resolv.conf itself —
    i.e. generateResolvConf hasn't been set to false in /etc/wsl.conf yet. False once it has, even
    if the file's *content* still shows the old "automatically generated by WSL" comment: WSL
    stops touching the file once that setting takes effect, it doesn't revert what's already
    there, so content alone isn't a reliable signal of what WSL will do next.
    """
    gen = _wsl_conf_value("network", "generateResolvConf")
    return not (gen is not None and gen.lower() == "false")


def _resolv_conf_symlinked_to_stub() -> bool:
    """Stock Ubuntu ships /etc/resolv.conf as a symlink to systemd-resolved's stub resolver.

    WSL's generateResolvConf overwrites that symlink with a plain file on every boot. Setting
    generateResolvConf=false only stops WSL from touching the file going forward — it does not
    restore the symlink, so the stale plain file (still containing the "automatically generated
    by WSL" comment, since nothing has rewritten it) is left in place. `inv system.dns` only
    edits systemd-resolved's own drop-in config, same as on bare metal, so with the symlink
    missing it has nothing to point at and DNS keeps failing (curl error 6) until the symlink is
    restored.
    """
    return _RESOLV_CONF.is_symlink() and os.path.realpath(_RESOLV_CONF) == os.path.realpath(_STUB_RESOLV_CONF)


def _dns_resolves(c) -> bool:
    """Actually test resolution, rather than trust that a correct config + a restarted service
    means it works. Seen in the wild under WSL2: systemd-resolved freshly configured and
    restarted, `resolvectl status` even showing the right DNS servers, and the stub at
    127.0.0.53 *still* not resolving anything — some WSL2 network configurations (mirrored
    networking mode, certain VPN/firewall setups) break the loopback stub specifically, even
    though raw connectivity (e.g. `ping 1.1.1.1`) is fine.
    """
    return c.run("getent hosts archive.ubuntu.com", warn=True, hide=True).ok


def _dns_query_packet(hostname: str, query_id: int) -> bytes:
    """Pure builder for a minimal DNS A-record query packet (header + QNAME + QTYPE/QCLASS) — no
    I/O, split out from _query_dns_server so it's testable without a live socket.
    """
    header = struct.pack(">HHHHHH", query_id, 0x0100, 1, 0, 0, 0)
    qname = b"".join(bytes([len(part)]) + part.encode() for part in hostname.split(".")) + b"\x00"
    return header + qname + struct.pack(">HH", 1, 1)  # type A, class IN


def _query_dns_server(server: str, hostname: str = "archive.ubuntu.com", timeout: float = 2.0) -> bool:
    """Send a raw DNS query straight to `server:53` over UDP, bypassing /etc/resolv.conf entirely
    — the only way to test "would public DNS work" *before* changing any config. _dns_resolves
    above always goes through the current system resolver, so it can only verify a config that's
    already been applied; this probes reachability first, non-destructively, so wsl.install/
    wsl.check can inform their DNS recommendation without a write + restart cycle to find out.
    Any well-formed response (even NXDOMAIN) counts as reachable; a timeout or connection error
    means the path is blocked or unreachable — the corporate-VPN/firewall signature from
    docs/wsl.md, "If public DNS is blocked".
    """
    query_id = os.getpid() & 0xFFFF
    packet = _dns_query_packet(hostname, query_id)
    try:
        with socket.socket(socket.AF_INET, socket.SOCK_DGRAM) as sock:
            sock.settimeout(timeout)
            sock.sendto(packet, (server, 53))
            data, _ = sock.recvfrom(512)
        return len(data) >= 2 and data[:2] == packet[:2]
    except OSError:
        return False


def _public_dns_reachable() -> bool:
    """True if a direct query to any well-known public resolver gets an answer. Informs (but,
    deliberately, never overrides) wsl.install's DNS default — see docs/wsl.md, "If public DNS is
    blocked": even when reachable, overriding WSL's own DNS can still break resolution of
    internal/VPN-only hostnames a corporate resolver knows about that public DNS never will, so
    reachability alone isn't proof the override is safe.
    """
    return any(_query_dns_server(server) for server in ("1.1.1.1", "8.8.8.8"))


def _write_static_resolv_conf(c, primary="1.1.1.1", secondary="1.0.0.1") -> None:
    """Bypass systemd-resolved's stub entirely: replace /etc/resolv.conf with a plain file
    pointing straight at public DNS servers. Fallback for when the stub isn't resolving anything
    even after system.dns() has configured and restarted systemd-resolved — see _dns_resolves.
    Loses systemd-resolved's integration (split DNS, mDNS, etc.) but this is the last resort after
    that's already been tried and failed.
    """
    with tempfile.NamedTemporaryFile("w", suffix=".conf", delete=False) as f:
        f.write(f"nameserver {primary}\nnameserver {secondary}\n")
        tmp = f.name
    c.run(f"{util.SUDO} rm -f {_RESOLV_CONF} && {util.SUDO} cp {tmp} {_RESOLV_CONF} && rm {tmp}")


def _wslg_available() -> bool:
    return Path("/mnt/wslg").exists() or bool(os.environ.get("WAYLAND_DISPLAY"))


def _os_release_id() -> str:
    try:
        text = Path("/etc/os-release").read_text()
    except FileNotFoundError:
        return ""
    for line in text.splitlines():
        if line.startswith("ID="):
            return line.partition("=")[2].strip().strip('"')
    return ""


@task
def check(c):
    """Diagnose WSL-specific risks before running PULSE tasks: systemd, DNS, Docker, WSLg.

    Read-only — reports findings and remediation, changes nothing. See docs/wsl.md.
    """
    if not util.is_wsl():
        print("[wsl] not running under WSL — nothing to check")
        return

    if _is_wsl2():
        print("[wsl] WSL2 detected")
    else:
        print(
            "[wsl] WSL1 detected  ← WARNING: WSL1 has no real Linux kernel (syscall translation "
            "layer only). systemd does not run under WSL1 at all, so every check below will fail "
            "and most of PULSE's system.* and docker.* tasks are not usable. Upgrade to WSL2:\n"
            "       wsl.exe --set-version <distro> 2   (run from Windows)"
        )

    # Distro — WSL isn't Ubuntu-only (Debian, Kali, Alpine, Fedora Remix, openSUSE, Arch are all
    # available from the Microsoft Store); PULSE assumes apt/dpkg everywhere (apt, apt-repo,
    # deb-github, deb-url methods) and Ubuntu specifically for apt.repos (uses `lsb_release -cs` as
    # the codename in repo source lines) and apt.base's package set.
    os_id = _os_release_id()
    if os_id == "ubuntu":
        print("[wsl] distro: Ubuntu ✓")
    elif util.command_exists("apt"):
        print(
            f"[wsl] distro: {os_id or 'unknown'} — has apt, but PULSE is only tested against "
            "Ubuntu 24.04.  ← apt/apt-repo/deb-github/deb-url methods should work; anything "
            "assuming Ubuntu specifically (apt.repos' `lsb_release -cs` codename in repo source "
            "lines, apt.base's exact package names) may not resolve or may pull the wrong repo."
        )
    else:
        print(
            f"[wsl] distro: {os_id or 'unknown'} — no `apt` found.  ← PULSE assumes apt/dpkg "
            "throughout (apt, apt-repo, deb-github, deb-url methods); almost none of this repo "
            "will work here as-is. Install Ubuntu-24.04 from the Microsoft Store instead:\n"
            "       wsl.exe --install Ubuntu-24.04   (run from Windows)"
        )

    # systemd — gates system.locale, system.dns, system.journal_size, docker.configure
    if _systemd_running():
        print("[wsl] systemd: running ✓")
    else:
        print(
            "[wsl] systemd: NOT running  ← system.locale, system.dns, system.journal-size, and "
            "docker.configure now abort immediately instead of failing partway (util.require_systemd).\n"
            "       Fix: `inv wsl.fix` sets systemd=true in /etc/wsl.conf, then `wsl.exe --shutdown` "
            "from Windows and reopen the terminal."
        )

    # DNS — WSL regenerates /etc/resolv.conf from the Windows host on every restart by default
    relink_cmd = f"sudo ln -sf {_STUB_RESOLV_CONF} /etc/resolv.conf"
    if _resolv_conf_wsl_active():
        print(
            "[wsl] resolv.conf: auto-generated by WSL  ← inv system.dns writes a systemd-resolved "
            "drop-in that will be silently overwritten on every WSL restart.\n"
            "       Fix (only if you actually want the public-DNS override — see the DNS "
            "reachability line below first): `inv wsl.fix --dns` sets generateResolvConf=false in "
            f"/etc/wsl.conf, then `wsl.exe --shutdown`, reopen, `{relink_cmd}`, and re-run "
            "`inv system.dns`."
        )
    elif _resolv_conf_symlinked_to_stub():
        print("[wsl] resolv.conf: not WSL-managed ✓ (inv system.dns is safe to use)")
    else:
        print(
            "[wsl] resolv.conf: generateResolvConf=false is set, but /etc/resolv.conf isn't a "
            "symlink to systemd-resolved's stub yet  ← inv system.dns edits systemd-resolved's own "
            "config and won't have any effect until this is fixed. If you just restarted, this is "
            "the stale file WSL left behind — WSL doesn't restore the symlink on its own.\n"
            f"       Fix: `{relink_cmd}` then `inv system.dns`."
        )

    # Public DNS reachability — a direct, non-destructive probe (bypasses /etc/resolv.conf
    # entirely), so this reports the same thing regardless of which DNS mode is currently active.
    # Informational only: even "reachable" doesn't mean overriding WSL's own DNS is safe, since it
    # can still break resolution of internal/VPN-only hostnames a corporate resolver knows about
    # that public DNS never will (split-horizon DNS) — see docs/wsl.md, "If public DNS is blocked".
    if _public_dns_reachable():
        print(
            "[wsl] public DNS (1.1.1.1/8.8.8.8): reachable — a direct UDP/53 query got an answer.\n"
            '       Still worth reading "If public DNS is blocked" in docs/wsl.md before opting '
            "into the override (`inv wsl.install --dns=yes` / `inv wsl.fix --dns`): reachability "
            "alone doesn't rule out breaking internal/VPN-only hostnames on a corporate network."
        )
    else:
        print(
            "[wsl] public DNS (1.1.1.1/8.8.8.8): NOT reachable from here (direct UDP/53 query "
            'timed out) — the corporate-VPN/firewall signature described in "If public DNS is '
            "blocked\" in docs/wsl.md. `inv wsl.install`'s default already leaves WSL's own DNS "
            "alone for this reason; the override isn't usable on this network."
        )

    # Docker — native dockerd (systemctl-manageable) vs Docker Desktop's WSL integration (CLI only)
    if not util.command_exists("docker"):
        print("[wsl] docker: not installed — nothing to check")
    elif util.is_docker_desktop_wsl_integration():
        print(
            "[wsl] docker: `docker` CLI found but no local dockerd — this looks like Docker "
            "Desktop's WSL integration.  ← docker.configure's `systemctl restart docker` will fail: "
            "there is no local docker.service to manage.\n"
            "       Either leave [packages.docker] excluded (workstation tag) and manage Docker "
            "Desktop settings from Windows, or install docker-ce natively in this distro "
            "(don't exclude the workstation tag) to use docker.configure as-is."
        )
    else:
        print("[wsl] docker: native dockerd found ✓ (docker.configure's systemctl calls apply normally)")

    # WSLg — gates GUI apps and Wayland clipboard
    if _wslg_available():
        print(
            "[wsl] WSLg: available ✓ — gui/desktop packages work, but install as little as "
            "possible: PULSE_EXCLUDE_TAGS=gnome,ide,windows-native,workstation,corporate\n"
            '       See docs/wsl.md, "GUI, WSLg, and clipboard" for why.'
        )
    else:
        print(
            "[wsl] WSLg: not detected — [packages.clipboard] (wl-clipboard) and any gui/desktop/gnome-"
            "tagged package will not work. Use PULSE_EXCLUDE_TAGS=gui,desktop,gnome,workstation,corporate."
        )

    # Fonts — cannot be checked or fixed from inside WSL; always worth the reminder
    print(
        "[wsl] fonts: inv fonts.install only installs into ~/.local/share/fonts inside this distro — "
        "invisible to Windows Terminal or any other Windows-side app. Install the Nerd Font on the "
        "Windows side manually for terminal glyphs to render correctly."
    )


@task
def fix(c, dns=False):
    """Fix common /etc/wsl.conf misconfigurations: systemd=true, generateResolvConf left at its
    safe default (true — WSL manages /etc/resolv.conf itself, mirroring whatever DNS server
    Windows itself uses).

    Only touches settings that are actually fixable from inside the distro — distro choice, WSL1
    vs WSL2, and WSLg availability all require action on the Windows side (see `inv wsl.check`
    for those). Requires a full WSL restart (`wsl.exe --shutdown` from Windows) to take effect.

    dns: pass --dns to set generateResolvConf=false instead, overriding WSL's own DNS with public
      resolvers (1.1.1.1 etc.) via systemd-resolved/inv system.dns. Defaults to leaving WSL's own
      DNS alone, same reasoning as `inv wsl.install`'s default (see docs/wsl.md, "If public DNS is
      blocked"): even when public DNS is reachable, overriding can still break resolution of
      internal/VPN-only hostnames a corporate resolver knows about that it never will. Only opt in
      if you know you don't need those — `inv wsl.check` reports whether public DNS is even
      reachable on this network as one data point, but reachability alone isn't proof it's safe.
    """
    if not util.is_wsl():
        print("[wsl] not running under WSL — nothing to fix")
        return

    dns_target = "false" if dns else "true"
    text = _WSL_CONF.read_text() if _WSL_CONF.exists() else ""
    new_text, systemd_changed = _ensure_wsl_conf_kv(text, "boot", "systemd", "true")
    new_text, dns_changed = _ensure_wsl_conf_kv(new_text, "network", "generateResolvConf", dns_target)

    if util.DRY_RUN:
        print(f"[wsl.fix] systemd=true: {util.ok_label(not systemd_changed)}")
        print(f"[wsl.fix] generateResolvConf={dns_target}: {util.ok_label(not dns_changed)}")
        return

    if not (systemd_changed or dns_changed):
        print(f"[wsl.fix] /etc/wsl.conf already has systemd=true and generateResolvConf={dns_target} — nothing to do")
        return

    with tempfile.NamedTemporaryFile("w", suffix=".conf", delete=False) as f:
        f.write(new_text)
        tmp = f.name
    c.run(f"{util.SUDO} mkdir -p {_WSL_CONF.parent} && {util.SUDO} cp {tmp} {_WSL_CONF} && rm {tmp}")

    fixed = ", ".join(
        name for name, changed in (("systemd", systemd_changed), ("generateResolvConf", dns_changed)) if changed
    )
    print(f"[wsl.fix] /etc/wsl.conf updated ({fixed})")
    print(
        "[wsl.fix] Takes effect only after a full WSL restart — from Windows (PowerShell/cmd, not "
        "from inside this distro): `wsl.exe --shutdown`, then reopen your terminal."
    )
    if dns_changed and dns:
        print(
            "[wsl.fix] After restarting: /etc/resolv.conf will still be the stale WSL-written file "
            "— WSL doesn't restore the systemd-resolved symlink on its own. Run "
            f"`sudo ln -sf {_STUB_RESOLV_CONF} /etc/resolv.conf` then `inv system.dns` "
            "(or just `inv wsl.install`, which does this for you) — see docs/wsl.md."
        )
    elif dns_changed and not dns:
        print(
            "[wsl.fix] After restarting: WSL will regenerate /etc/resolv.conf itself from the "
            "Windows host's own DNS settings — nothing else to run, don't call `inv system.dns`."
        )


@task
def install(c, wslg="auto", docker=False, dns="auto"):
    """Run the docs/wsl.md recommended install sequence in one shot, as named phases: wsl config,
    system config (locale/DNS, only if systemd/DNS are actually live yet), packages, then shell —
    with WSL-appropriate tags excluded.

    This exists instead of pasting the multi-line sequence from docs/wsl.md into a terminal:
    that sequence is a series of separate `inv` invocations, so if one of them hangs (e.g. a
    network problem mid-apt) and you Ctrl-C it, the shell just moves on to the next already-
    pasted line rather than stopping — it looks like Ctrl-C "did nothing". Running everything
    as task calls inside one invoke process means Ctrl-C here aborts the whole thing.

    In a real terminal (not piped/scripted/CI), asks before doing anything: the DNS question below
    if `dns` is left at "auto" (defaults to declining the public-DNS override — see `dns` below),
    then a one-line summary of what's about to happen and a final "Proceed?" (defaults to yes). On
    a re-run — e.g. after the WSL restart that `/etc/wsl.conf` changes require — the packages and
    shell phases each probe whether they already look done and, if so, offer to skip (default:
    skip) instead of redoing apt/tool/zsh work that already succeeded (see tasks/phases.py).

    wslg: "auto" (default, detected the same way `inv wsl.check` does), "yes", or "no" — controls
      which tag set is excluded (see docs/wsl.md, "Tags to exclude").
    docker: pass --docker to also install Docker natively (drops the `workstation` tag exclusion)
      instead of leaving Docker to Docker Desktop's WSL integration.
    dns: "auto" (default) — probes whether public DNS (1.1.1.1/8.8.8.8) is directly reachable on
      this network (informational only), then asks whether to override WSL's own DNS with it,
      defaulting to **no** either way — even when reachable, the override can break resolution of
      internal/VPN-only hostnames a corporate resolver knows about that public DNS never will (see
      docs/wsl.md, "If public DNS is blocked"). Non-interactive (piped/scripted/CI) always picks
      "no" without asking. "yes" (force the override, skip the probe/prompt) or "no" (explicit,
      same as the auto default — skip straight to WSL-managed DNS).
    """
    if not util.is_wsl():
        print("[wsl.install] not running under WSL — nothing to do")
        return

    if dns == "auto":
        public_dns_ok = _public_dns_reachable()
        print(
            "[wsl.install] public DNS (1.1.1.1/8.8.8.8): "
            + ("reachable" if public_dns_ok else "NOT reachable")
            + " from this network (direct UDP/53 probe)"
        )
        if public_dns_ok:
            explanation = (
                "A direct query to public DNS got an answer, so the override is likely usable "
                "here — but it can still break resolution of internal/VPN-only hostnames a "
                "corporate resolver knows about that public DNS never will. Defaulting to leave "
                "WSL's own DNS alone (mirrors whatever Windows itself resolves) unless you know "
                "you don't need those.\nOverride WSL's own DNS with public resolvers anyway?"
            )
        else:
            explanation = (
                "A direct query to public DNS got no answer — the signature of a corporate VPN/"
                "firewall that allows general traffic but blocks DNS (UDP 53) to anything but its "
                "own resolver. Overriding WSL's own DNS is very likely to just break resolution "
                "here.\nOverride WSL's own DNS with public resolvers anyway?"
            )
        use_public_dns = ui.ask(explanation, default=False)
    else:
        use_public_dns = _parse_tristate(dns, "dns")

    ui.block(
        "About to: configure /etc/wsl.conf (systemd"
        + (", public DNS with automatic fallback" if use_public_dns else ", WSL-managed DNS")
        + "), install apt packages/dev tools/Node/zsh with WSL-appropriate tags excluded, "
        "and set zsh as your login shell.",
        label="wsl.install",
    )
    if not ui.ask("Proceed?", default=True):
        print("[wsl.install] aborted")
        return

    if not os.environ.get("SUDO_ASKPASS") and not util.DRY_RUN:
        # Every other sudo call below runs through invoke's non-interactive Runner, which doesn't
        # give the child process a real tty — sudo can't read a password from that (it prints the
        # prompt, then fails immediately with "a password is required"), even for calls that
        # aren't piped. Warming up sudo's credential cache here, in a real pty, means those later
        # calls succeed without prompting at all as long as the cache stays valid (~15min default;
        # re-run `sudo -v` in another terminal, or just re-run `inv wsl.install`, if it lapses on
        # a slow connection).
        print("[wsl.install] pre-authenticating sudo — enter your password if asked:")
        c.run(f"{util.SUDO} -v", pty=True)

    check(c)

    ui.block(
        "/etc/wsl.conf: systemd, DNS mode. Requires a full WSL restart (wsl.exe --shutdown) to take effect.",
        label="phase: wsl config",
    )
    pre = (_wsl_conf_value("boot", "systemd"), _wsl_conf_value("network", "generateResolvConf"))
    fix(c, dns=use_public_dns)
    post = (_wsl_conf_value("boot", "systemd"), _wsl_conf_value("network", "generateResolvConf"))
    if pre != post:
        ui.warn(
            "/etc/wsl.conf just changed — system.locale"
            + ("/system.dns" if use_public_dns else "")
            + " below will be skipped until you `wsl.exe --shutdown` (from Windows) and reopen, "
            "then re-run `inv wsl.install`. Continuing with the rest of the install now."
        )

    # Fix locale/DNS *before* anything network-dependent below (apt, tools.install, node, zsh's
    # oh-my-zsh clone, ...): if this is a re-run after a restart and generateResolvConf=false is
    # already live, DNS is broken (stale resolv.conf, see _resolv_conf_symlinked_to_stub) until
    # this runs — doing it last meant every one of those steps hit the same DNS failure first.
    ui.block(
        "Locale and DNS — skipped automatically below until systemd/DNS are actually live post-restart.",
        label="phase: system config",
    )
    if _systemd_running():
        system.locale(c)
    else:
        print("[wsl.install] systemd not live yet — skipping system.locale (restart WSL and re-run)")

    if not use_public_dns:
        print("[wsl.install] leaving /etc/resolv.conf to WSL's own generateResolvConf")
    elif _systemd_running() and not _resolv_conf_wsl_active():
        if not _resolv_conf_symlinked_to_stub():
            if util.DRY_RUN:
                print("[wsl.install] /etc/resolv.conf: MISSING symlink to stub-resolv.conf")
            else:
                c.run(f"{util.SUDO} ln -sf {_STUB_RESOLV_CONF} {_RESOLV_CONF}")
                print(f"[wsl.install] relinked /etc/resolv.conf -> {_STUB_RESOLV_CONF}")
        system.dns(c)
        if util.DRY_RUN:
            pass
        elif _dns_resolves(c):
            print("[wsl.install] DNS resolution verified working")
        else:
            print(
                "[wsl.install] systemd-resolved is configured and restarted, but DNS still isn't "
                "resolving — falling back to a static /etc/resolv.conf (bypassing the stub)"
            )
            _write_static_resolv_conf(c)
            if _dns_resolves(c):
                print("[wsl.install] DNS resolution verified working (static /etc/resolv.conf)")
            else:
                ui.warn(
                    "DNS still isn't resolving even against a static resolv.conf pointed straight "
                    "at 1.1.1.1 — if `ping 1.1.1.1` works but this doesn't, your network is very "
                    "likely blocking DNS to public resolvers (common on corporate VPNs/firewalls). "
                    "Public DNS isn't usable here at all — re-run as `inv wsl.install --dns=no`, "
                    "restart WSL, and let WSL manage /etc/resolv.conf itself by mirroring the "
                    "Windows host's own (working) DNS server instead."
                )
    else:
        print("[wsl.install] systemd/DNS not both live yet — skipping system.dns (restart WSL and re-run)")

    use_wslg = _wslg_available() if wslg == "auto" else _parse_tristate(wslg, "wslg")

    if use_wslg:
        excluded = {"gnome", "ide", "windows-native", "workstation", "corporate"}
    else:
        excluded = {"gui", "desktop", "gnome", "workstation", "corporate"}
    if docker:
        excluded.discard("workstation")

    if "PULSE_EXCLUDE_TAGS" in os.environ:
        print(
            f"[wsl.install] PULSE_EXCLUDE_TAGS already set in the environment "
            f"({os.environ['PULSE_EXCLUDE_TAGS']!r}) — using it as-is instead of the WSL default"
        )
    else:
        os.environ["PULSE_EXCLUDE_TAGS"] = ",".join(sorted(excluded))
        print(f"[wsl.install] PULSE_EXCLUDE_TAGS={os.environ['PULSE_EXCLUDE_TAGS']}")

    phases.run_phase(
        c,
        "packages",
        [apt.repos, apt.base, apt.deb, tools.install, ai.skills, python.tools, node.install, verify.all],
        note=(
            "apt repos/packages, script/binary tools, AI agent skills scaffolding, Python and "
            "Node.js, then a hard functional-verification pass over everything just installed"
        ),
    )

    phases.run_phase(
        c,
        "shell",
        [zsh.omz_configure, zsh.configure, zsh.p10k_configure, zsh.set_default_shell],
        note="Oh My Zsh theme/plugins, zsh config blocks, Powerlevel10k baseline, default shell",
    )

    if docker:
        ui.note("--docker: run `inv docker.configure` once systemd is confirmed live (`inv wsl.check`).")

    next_steps.print_next_steps(
        extra_note="Install a Nerd Font on the Windows side for Powerlevel10k icons to render in "
        "Windows Terminal — see docs/wsl.md."
    )
