import os
from pathlib import Path

from invoke import task

from . import util

_WSL_CONF   = Path("/etc/wsl.conf")
_RESOLV_CONF = Path("/etc/resolv.conf")
_PROC_VERSION  = Path("/proc/version")
_OSRELEASE     = Path("/proc/sys/kernel/osrelease")


def _is_wsl() -> bool:
    if os.environ.get("WSL_DISTRO_NAME") or os.environ.get("WSL_INTEROP"):
        return True
    try:
        return "microsoft" in _PROC_VERSION.read_text().lower()
    except FileNotFoundError:
        return False


def _is_wsl2() -> bool:
    try:
        release = _OSRELEASE.read_text().lower()
    except FileNotFoundError:
        return False
    return "wsl2" in release or "microsoft-standard" in release


def _systemd_running() -> bool:
    return Path("/run/systemd/system").is_dir()


def _wsl_conf_value(section: str, key: str) -> str | None:
    """Read a single key out of /etc/wsl.conf's INI format. Returns None if unset."""
    if not _WSL_CONF.exists():
        return None
    current = None
    for line in _WSL_CONF.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or line.startswith(";"):
            continue
        if line.startswith("[") and line.endswith("]"):
            current = line[1:-1].strip().lower()
            continue
        if current == section and "=" in line:
            k, _, v = line.partition("=")
            if k.strip().lower() == key.lower():
                return v.strip()
    return None


def _resolv_conf_is_wsl_generated() -> bool:
    try:
        text = _RESOLV_CONF.read_text().lower()
    except FileNotFoundError:
        return False
    return "automatically generated by wsl" in text


def _wslg_available() -> bool:
    return Path("/mnt/wslg").exists() or bool(os.environ.get("WAYLAND_DISPLAY"))


def _os_release_id() -> str:
    try:
        text = Path("/etc/os-release").read_text()
    except FileNotFoundError:
        return ""
    for line in text.splitlines():
        if line.startswith("ID="):
            return line.partition("=")[2].strip().strip('"')
    return ""


@task
def check(c):
    """Diagnose WSL-specific risks before running PULSE tasks: systemd, DNS, Docker, WSLg.

    Read-only — reports findings and remediation, changes nothing. See docs/wsl.md.
    """
    if not _is_wsl():
        print("[wsl] not running under WSL — nothing to check")
        return

    if _is_wsl2():
        print("[wsl] WSL2 detected")
    else:
        print(
            "[wsl] WSL1 detected  ← WARNING: WSL1 has no real Linux kernel (syscall translation "
            "layer only). systemd does not run under WSL1 at all, so every check below will fail "
            "and most of PULSE's system.* and docker.* tasks are not usable. Upgrade to WSL2:\n"
            "       wsl.exe --set-version <distro> 2   (run from Windows)"
        )

    # Distro — WSL isn't Ubuntu-only (Debian, Kali, Alpine, Fedora Remix, openSUSE, Arch are all
    # available from the Microsoft Store); PULSE assumes apt/dpkg everywhere (apt, apt-repo,
    # deb-github, deb-url methods) and Ubuntu specifically for apt.repos (uses `lsb_release -cs` as
    # the codename in repo source lines) and apt.base's package set.
    os_id = _os_release_id()
    if os_id == "ubuntu":
        print("[wsl] distro: Ubuntu ✓")
    elif util.command_exists("apt"):
        print(
            f"[wsl] distro: {os_id or 'unknown'} — has apt, but PULSE is only tested against "
            "Ubuntu 24.04.  ← apt/apt-repo/deb-github/deb-url methods should work; anything "
            "assuming Ubuntu specifically (apt.repos' `lsb_release -cs` codename in repo source "
            "lines, apt.base's exact package names) may not resolve or may pull the wrong repo."
        )
    else:
        print(
            f"[wsl] distro: {os_id or 'unknown'} — no `apt` found.  ← PULSE assumes apt/dpkg "
            "throughout (apt, apt-repo, deb-github, deb-url methods); almost none of this repo "
            "will work here as-is. Install Ubuntu-24.04 from the Microsoft Store instead:\n"
            "       wsl.exe --install Ubuntu-24.04   (run from Windows)"
        )

    # systemd — gates system.locale, system.dns, system.journal_size, docker.configure
    if _systemd_running():
        print("[wsl] systemd: running ✓")
    else:
        print(
            "[wsl] systemd: NOT running  ← system.locale (localectl), system.dns and "
            "system.journal-size (systemctl), and docker.configure's systemctl restart will all fail.\n"
            "       Fix: add to /etc/wsl.conf —\n"
            "         [boot]\n"
            "         systemd=true\n"
            "       then run `wsl.exe --shutdown` from Windows and reopen the terminal."
        )

    # DNS — WSL regenerates /etc/resolv.conf from the Windows host on every restart by default
    if _resolv_conf_is_wsl_generated():
        gen = _wsl_conf_value("network", "generateResolvConf")
        already_disabled = gen is not None and gen.lower() == "false"
        if already_disabled:
            print(
                "[wsl] resolv.conf: still WSL-generated even though generateResolvConf=false is set "
                "— re-check /etc/wsl.conf, or run `wsl.exe --shutdown` and reopen if you just changed it."
            )
        else:
            print(
                "[wsl] resolv.conf: auto-generated by WSL  ← inv system.dns writes a systemd-resolved "
                "drop-in that will be silently overwritten on every WSL restart.\n"
                "       Fix: add to /etc/wsl.conf —\n"
                "         [network]\n"
                "         generateResolvConf = false\n"
                "       then `wsl.exe --shutdown`, reopen, delete the stale /etc/resolv.conf, and "
                "re-run `inv system.dns`."
            )
    else:
        print("[wsl] resolv.conf: not WSL-managed ✓ (inv system.dns is safe to use)")

    # Docker — native dockerd (systemctl-manageable) vs Docker Desktop's WSL integration (CLI only)
    if util.command_exists("docker"):
        if util.command_exists("dockerd"):
            print("[wsl] docker: native dockerd found ✓ (docker.configure's systemctl calls apply normally)")
        else:
            print(
                "[wsl] docker: `docker` CLI found but no local dockerd — this looks like Docker "
                "Desktop's WSL integration.  ← docker.configure's `systemctl restart docker` will fail: "
                "there is no local docker.service to manage.\n"
                "       Either leave [packages.docker] excluded (workstation tag) and manage Docker "
                "Desktop settings from Windows, or install docker-ce natively in this distro "
                "(don't exclude the workstation tag) to use docker.configure as-is."
            )
    else:
        print("[wsl] docker: not installed — nothing to check")

    # WSLg — gates GUI apps and Wayland clipboard
    if _wslg_available():
        print("[wsl] WSLg: available ✓ — wl-clipboard and GUI apps may work, but untested by PULSE")
    else:
        print(
            "[wsl] WSLg: not detected — [packages.clipboard] (wl-clipboard) and any gui/desktop/gnome-"
            "tagged package will not work. Use PULSE_EXCLUDE_TAGS=gui,desktop,gnome,workstation,corporate."
        )

    # Fonts — cannot be checked or fixed from inside WSL; always worth the reminder
    print(
        "[wsl] fonts: inv fonts.install only installs into ~/.local/share/fonts inside this distro — "
        "invisible to Windows Terminal or any other Windows-side app. Install the Nerd Font on the "
        "Windows side manually for terminal glyphs to render correctly."
    )
